name: irohasu
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  html: ^0.15.0
  photo_view: ^0.13.0
  bottom_navy_bar: ^6.0.0
  snapping_sheet: ^3.1.0
  cached_network_image: ^3.2.0

  # State management
  flutter_bloc: ^8.0.1

  # Caching
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # Value equality
  equatable: ^2.0.3

  # Functional programming
  dartz: ^0.10.1

  # Remote API
  dio: ^4.0.4

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Misc
  rxdart: ^0.27.3
  path_provider: ^2.0.3
  intl: ^0.17.0
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/404.png
    - assets/images/default_image.jpeg

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-Black.ttf
          weight: 900
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
