name: irohasu
description: A new Flutter project.

publish_to: "none"

version: 0.5.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  html: ^0.15.0
  bottom_navy_bar: ^6.0.0
  snapping_sheet: ^3.1.0
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Value equality
  equatable: ^2.0.3

  # Functional programming
  dartz: ^0.10.1

  # Remote API
  dio: ^4.0.6

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Dart data class
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

  # Misc
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  intl: ^0.17.0
  scrollable_positioned_list: ^0.3.2
  collection: ^1.16.0

  # Info package
  package_info_plus: ^1.4.2
  device_info: ^2.0.3

  # Network
  connectivity_plus: ^2.3.6

  # Download file
  flutter_downloader: ^1.7.4

  # Markdown renderer
  flutter_markdown: ^0.6.10+3

  # Permission app
  permission_handler: ^10.0.0

  # Logger
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4

  # Linting
  flutter_lints: ^2.0.1

  # Testing
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

dependency_overrides:
  analyzer: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/404.png
    - assets/images/default_image.jpeg

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-Black.ttf
          weight: 900
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
