name: irohasu
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^4.0.4
  # flutter_webview_plugin: ^0.4.0
  rxdart: ^0.27.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  scrollable_positioned_list: ^0.2.3
  bottom_navy_bar: ^6.0.0
  snapping_sheet: ^3.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  html: ^0.15.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/404.png
    - assets/images/default_image.jpeg

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
        - asset: assets/fonts/BeVietnamPro-Light.ttf
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
